# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1478, 958)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: \"#E5F1FB\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widgetPaint = QtWidgets.QWidget(self.centralwidget)
        self.widgetPaint.setGeometry(QtCore.QRect(10, 10, 1461, 771))
        self.widgetPaint.setStyleSheet("background-color: \"gray\";")
        self.widgetPaint.setObjectName("widgetPaint")
        self.scrollArea = QtWidgets.QScrollArea(self.widgetPaint)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1471, 771))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1469, 769))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.graphicsViewPaint = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.graphicsViewPaint.setGeometry(QtCore.QRect(0, -2, 1461, 771))
        self.graphicsViewPaint.setStyleSheet("background-color: \"#EEEEEC\";")
        self.graphicsViewPaint.setObjectName("graphicsViewPaint")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.groupBoxControl = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxControl.setGeometry(QtCore.QRect(10, 790, 1461, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxControl.setFont(font)
        self.groupBoxControl.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBoxControl.setStyleSheet("background-color: \"#CDCDCD\";")
        self.groupBoxControl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxControl.setFlat(True)
        self.groupBoxControl.setCheckable(False)
        self.groupBoxControl.setObjectName("groupBoxControl")
        self.lblPoint = QtWidgets.QLabel(self.groupBoxControl)
        self.lblPoint.setGeometry(QtCore.QRect(90, 30, 55, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lblPoint.setFont(font)
        self.lblPoint.setObjectName("lblPoint")
        self.lblNodes = QtWidgets.QLabel(self.groupBoxControl)
        self.lblNodes.setGeometry(QtCore.QRect(1060, 60, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblNodes.setFont(font)
        self.lblNodes.setObjectName("lblNodes")
        self.lblLine = QtWidgets.QLabel(self.groupBoxControl)
        self.lblLine.setGeometry(QtCore.QRect(90, 70, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblLine.setFont(font)
        self.lblLine.setObjectName("lblLine")
        self.lblSteps = QtWidgets.QLabel(self.groupBoxControl)
        self.lblSteps.setGeometry(QtCore.QRect(1060, 30, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSteps.setFont(font)
        self.lblSteps.setObjectName("lblSteps")
        self.lblPointEnd = QtWidgets.QLabel(self.groupBoxControl)
        self.lblPointEnd.setGeometry(QtCore.QRect(830, 60, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblPointEnd.setFont(font)
        self.lblPointEnd.setObjectName("lblPointEnd")
        self.lblPointStart = QtWidgets.QLabel(self.groupBoxControl)
        self.lblPointStart.setGeometry(QtCore.QRect(830, 30, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblPointStart.setFont(font)
        self.lblPointStart.setObjectName("lblPointStart")
        self.lblStatus = QtWidgets.QLabel(self.groupBoxControl)
        self.lblStatus.setGeometry(QtCore.QRect(1130, 140, 331, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        self.lblStatus.setFont(font)
        self.lblStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblStatus.setObjectName("lblStatus")
        self.btnGenerate = QtWidgets.QPushButton(self.groupBoxControl)
        self.btnGenerate.setGeometry(QtCore.QRect(312, 110, 191, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnGenerate.setFont(font)
        self.btnGenerate.setStyleSheet("background-color: \"#E5E5E5\";")
        self.btnGenerate.setObjectName("btnGenerate")
        self.btnFind = QtWidgets.QPushButton(self.groupBoxControl)
        self.btnFind.setGeometry(QtCore.QRect(520, 110, 191, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btnFind.setFont(font)
        self.btnFind.setStyleSheet("background-color: \"#E5E5E5\";")
        self.btnFind.setObjectName("btnFind")
        self.lineEditPoint = QtWidgets.QLineEdit(self.groupBoxControl)
        self.lineEditPoint.setGeometry(QtCore.QRect(170, 21, 171, 31))
        self.lineEditPoint.setStyleSheet("background-color: \"#E5E5E5\";")
        self.lineEditPoint.setObjectName("lineEditPoint")
        self.lineEditLine = QtWidgets.QLineEdit(self.groupBoxControl)
        self.lineEditLine.setGeometry(QtCore.QRect(170, 60, 171, 31))
        self.lineEditLine.setStyleSheet("background-color: \"#E5E5E5\";")
        self.lineEditLine.setObjectName("lineEditLine")
        self.cbxShowSteps = QtWidgets.QCheckBox(self.groupBoxControl)
        self.cbxShowSteps.setGeometry(QtCore.QRect(410, 50, 161, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.cbxShowSteps.setFont(font)
        self.cbxShowSteps.setObjectName("cbxShowSteps")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dijkstra GUI PyQt5 development by vuongdq85"))
        self.groupBoxControl.setTitle(_translate("MainWindow", "Control"))
        self.lblPoint.setText(_translate("MainWindow", "Point:"))
        self.lblNodes.setText(_translate("MainWindow", "Nodes:"))
        self.lblLine.setText(_translate("MainWindow", "Line:"))
        self.lblSteps.setText(_translate("MainWindow", "Steps:"))
        self.lblPointEnd.setText(_translate("MainWindow", "Point end:"))
        self.lblPointStart.setText(_translate("MainWindow", "Point start:"))
        self.lblStatus.setText(_translate("MainWindow", "vuongdq85"))
        self.btnGenerate.setText(_translate("MainWindow", "Generate"))
        self.btnFind.setText(_translate("MainWindow", "Find"))
        self.lineEditPoint.setText(_translate("MainWindow", "7"))
        self.lineEditLine.setText(_translate("MainWindow", "16"))
        self.cbxShowSteps.setText(_translate("MainWindow", "Show steps"))
